name: Check free games
on:
  schedule:
    - cron: "0 13 * * *" # every day at 13:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: bun run src/index.ts
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
          EPIC_GAMES_FREE_GAMES_URL: https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions
